# Generated by Django 2.2 on 2021-03-31 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='课程名')),
                ('about', models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='课程描述')),
                ('leibie', models.CharField(max_length=40, verbose_name='课程类别')),
            ],
        ),
        migrations.CreateModel(
            name='Img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='img', verbose_name='图像')),
                ('name', models.CharField(blank=True, default='', max_length=40, null=True, verbose_name='图像名')),
            ],
        ),
        migrations.CreateModel(
            name='Maker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='制作者')),
                ('school', models.CharField(blank=True, default='', max_length=40, null=True, verbose_name='所属学校')),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='章节名')),
                ('about', models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='章节描述')),
                ('text', models.TextField(verbose_name='章节文本')),
                ('link', models.TextField(blank=True, default='', null=True, verbose_name='章节链接')),
                ('img', models.ImageField(upload_to='img', verbose_name='思维导图')),
                ('img_name', models.CharField(blank=True, default='', max_length=40, null=True, verbose_name='导图名')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='read.Course')),
                ('maker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='read.Maker')),
            ],
        ),
    ]
